version: '3'
services:
  web:
    # network_mode: "host"      
    build:
      context: .
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'

