---
apiVersion: v1
kind: Service
metadata:
  name: reguspop-redis-service
spec:
  selector:
    app.kubernetes.io/instance: web-reguspop-redis
  type: LoadBalancer
  loadBalancerIP: 172.22.24.55
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
