redis:
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.2

  architecture: replication
  auth:
    enabled: true
    sentinel: true
    password: '#AWp#&78XM7tp#g'

  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
  existingConfigmap: ''
  master:
    count: 1
    persistence:
      enabled: true

  replica:
    replicaCount: 2
    resources:
      limits: {}
      #   cpu: 250m
      #   memory: 256Mi
      requests: {}
      #   cpu: 250m
      #   memory: 256Mi
    persistence:
      enabled: true

  sentinel:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-sentinel
      tag: 7.2
    quorum: 2

  metrics:
    enabled: true
