version: '3'
services:
  redis-master:
    image: 'bitnami/redis:7.2'
    container_name: redis-master
    hostname: redis-master
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes

  redis-replica:
    image: 'bitnami/redis:7.2'
    deploy:
      replicas: 2
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes

  redis-sentinel:
    image: 'bitnami/redis-sentinel:7.2'
    deploy:
      replicas: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - '26379-26381'


  
