version: '3'
services:
  redis-master:
    image: 'bitnami/redis:7.2'
    container_name: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis

  # redis-slave-1:
  #   image: 'bitnami/redis:7.2'
  #   container_name: redis-slave-1
  #   network_mode: host
  #   depends_on:
  #     - redis-master
  #   environment:
  #     - REDIS_REPLICATION_MODE=slave
  #     - REDIS_MASTER_HOST=localhost
  #     # - REDIS_MASTER_PORT_NUMBER=6379
  #     - REDIS_DEFAULT_PORT_NUMBER=6380
  #     - ALLOW_EMPTY_PASSWORD=yes
  
  # redis-slave-2:
  #   image: 'bitnami/redis:7.2'
  #   container_name: redis-slave-2
  #   network_mode: host
  #   depends_on:
  #     - redis-master
  #   environment:
  #     - REDIS_REPLICATION_MODE=slave
  #     - REDIS_MASTER_HOST=localhost
  #     # - REDIS_MASTER_PORT_NUMBER=6379
  #     - REDIS_DEFAULT_PORT_NUMBER=6381
  #     - ALLOW_EMPTY_PASSWORD=yes
  
networks:
  redis:
    driver: host
